image: node:10.13

.docker_dind_tag_definition: &docker_dind_tag_definition
  tags:
    - docker-dind


before_script:
  - yarn

pages:
  cache:
    paths:
      - node_modules/
  only:
    - master
  <<: *docker_dind_tag_definition
  stage: deploy
  script:
    - echo "DID NOTHING"
  artifacts:
    paths:
      - public
